// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vatytrfgxvsqjeheheoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdHl0cmZneHZzcWplaGVoZW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjIyNzAsImV4cCI6MjA2Nzk5ODI3MH0.qRw4rV8nV9SNRdFHjoALecgbYf3b9bsANSYT2i9nGEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});